[build]
builder = "nixpacks"

[deploy]
startCommand = "node src/server.js"
watchPatterns = ["backend/**"]
restartPolicyType = "on_failure"

[build.env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"