-- Add missing columns to bookings table
ALTER TABLE bookings 
ADD COLUMN IF NOT EXISTS "Booking_Type" VARCHAR,
ADD COLUMN IF NOT EXISTS "Purpose" VARCHAR,
ADD COLUMN IF NOT EXISTS "Notes" TEXT,
ADD COLUMN IF NOT EXISTS "Is_Locked" BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "Locked_Until" TIMESTAMP;