version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: smartdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@database:5432/smartdesk
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    depends_on:
      - database
    ports:
      - "3001:3001"

  frontend:
    build: .
    environment:
      VITE_API_URL: http://backend:3001/api
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: